package cuc.edu.taller_desarr_tres;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TallerTres extends javax.swing.JFrame {

    Calificaciones lista_calificaciones = new Calificaciones();
    DefaultTableModel modelo = new DefaultTableModel();

    public TallerTres() {
        initComponents();
        //Inicio configuración de la tabla
        String[] identifiers = {"Nombre", "Nota 1", "Nota 2", "Nota 3", "Nota 4"};
        modelo.setColumnIdentifiers(identifiers);
        modelo.setRowCount(0);
        tablaCalificaciones.setModel(modelo);
        //Fin configuración de la tabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDos = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNotaUno = new javax.swing.JLabel();
        lblNotaDos = new javax.swing.JLabel();
        lblNotaTres = new javax.swing.JLabel();
        lblNotaCuatro = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNotaUno = new javax.swing.JTextField();
        txtNotaDos = new javax.swing.JTextField();
        txtNotaTres = new javax.swing.JTextField();
        txtNotaCuatro = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMenor = new javax.swing.JButton();
        btnAprobados = new javax.swing.JButton();
        panelUno = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCalificaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitulo.setText("Gestor de calificaciones");

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNombre.setText("Nombre del estudiante:");

        lblNotaUno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNotaUno.setText("Nota 1:");

        lblNotaDos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNotaDos.setText("Nota 2:");

        lblNotaTres.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNotaTres.setText("Nota 3:");

        lblNotaCuatro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNotaCuatro.setText("Nota 4:");

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtNotaUno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtNotaDos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtNotaTres.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtNotaCuatro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnAgregar.setText("Agregar estudiante");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar estudiante");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar estudiante");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnMenor.setText("Menor promedio");
        btnMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorActionPerformed(evt);
            }
        });

        btnAprobados.setText("Número de aprobados");
        btnAprobados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDosLayout = new javax.swing.GroupLayout(panelDos);
        panelDos.setLayout(panelDosLayout);
        panelDosLayout.setHorizontalGroup(
            panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitulo)
                        .addGroup(panelDosLayout.createSequentialGroup()
                            .addComponent(lblNombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDosLayout.createSequentialGroup()
                            .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelDosLayout.createSequentialGroup()
                                    .addComponent(lblNotaUno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNotaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelDosLayout.createSequentialGroup()
                                    .addComponent(lblNotaDos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNotaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelDosLayout.createSequentialGroup()
                                    .addComponent(lblNotaTres)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNotaTres, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelDosLayout.createSequentialGroup()
                                    .addComponent(lblNotaCuatro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNotaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(29, 29, 29)))
                    .addGroup(panelDosLayout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(panelDosLayout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMenor))
                    .addComponent(btnAprobados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDosLayout.setVerticalGroup(
            panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotaUno)
                    .addComponent(txtNotaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotaDos)
                    .addComponent(txtNotaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotaTres)
                    .addComponent(txtNotaTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotaCuatro)
                    .addComponent(txtNotaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnMenor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAprobados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelUno.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitulo1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitulo1.setText("Gestor de calificaciones");

        tablaCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCalificaciones);

        javax.swing.GroupLayout panelUnoLayout = new javax.swing.GroupLayout(panelUno);
        panelUno.setLayout(panelUnoLayout);
        panelUnoLayout.setHorizontalGroup(
            panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(panelUnoLayout.createSequentialGroup()
                        .addComponent(lblTitulo1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelUnoLayout.setVerticalGroup(
            panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Estudiante estudiante = crearEstudiante();
        if (estudiante != null) {
            if (lista_calificaciones.adicionarEstudainte(estudiante)) {
                JOptionPane.showMessageDialog(this, "Estudiante correctamente agregado", "exito", 1);
                actualizarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Estudiante en lista", "error", 0);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Nombre: ", "buscar", 1);
        if (nombre != null) {
            Estudiante estudiante = lista_calificaciones.buscarPorNombre(nombre);
            if (estudiante != null) {
                JOptionPane.showMessageDialog(this, "Nota 1: " + estudiante.nota_uno
                        + "\nNota 2: " + estudiante.nota_dos
                        + "\nNota 3: " + estudiante.nota_tres
                        + "\nNota 4: " + estudiante.nota_cuatro, "resultado", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Estudiante no encontrado", "error", 0);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila_seleccionada = tablaCalificaciones.getSelectedRow();
        if (fila_seleccionada != -1) {
            String nombre = lista_calificaciones.buscarPorPosicion(fila_seleccionada).getNombre();
            lista_calificaciones.sacarEstudiante(nombre);
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un estudiante en la tabla", "error", 0);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorActionPerformed
        Estudiante estudiante_menor_promerio = lista_calificaciones.menorPromedio();
        if (estudiante_menor_promerio != null) {
            JOptionPane.showMessageDialog(this, "Menor promedio: " + lista_calificaciones.menorPromedio().nombre, "info", 1);
        } else {
            JOptionPane.showMessageDialog(this, "Algo ha salido mal", "error", 0);
        }
    }//GEN-LAST:event_btnMenorActionPerformed

    private void btnAprobadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobadosActionPerformed
        JOptionPane.showMessageDialog(this, "El número de aprobados es: " + lista_calificaciones.numeroAprobados(), "info", 1);
    }//GEN-LAST:event_btnAprobadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TallerTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TallerTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TallerTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TallerTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TallerTres().setVisible(true);
            }
        });
    }

    public Estudiante crearEstudiante() {
        String nombre = txtNombre.getText();
        Double nota_uno, nota_dos, nota_tres, nota_cuatro;
        try {
            if (txtNotaUno.getText().equals("")) {
                nota_uno = 0.0;
            } else {
                nota_uno = Double.parseDouble(txtNotaUno.getText());
            }
            if (txtNotaDos.getText().equals("")) {
                nota_dos = 0.0;
            } else {
                nota_dos = Double.parseDouble(txtNotaDos.getText());
            }
            if (txtNotaTres.getText().equals("")) {
                nota_tres = 0.0;
            } else {
                nota_tres = Double.parseDouble(txtNotaTres.getText());
            }
            if (txtNotaCuatro.getText().equals("")) {
                nota_cuatro = 0.0;
            } else {
                nota_cuatro = Double.parseDouble(txtNotaCuatro.getText());
            }
            Estudiante estudiante = new Estudiante(nombre, nota_uno, nota_dos, nota_tres, nota_cuatro);
            return estudiante;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Algo ha salido mal, revisa las calificaciones", "error", 0);
            return null;
        }
    }

    public void actualizarTabla() {
        modelo.setRowCount(lista_calificaciones.numeroEstudiantes());
        for (int i = 0; i < tablaCalificaciones.getRowCount(); i++) {
            Estudiante estudiante = lista_calificaciones.buscarPorPosicion(i);
            tablaCalificaciones.setValueAt(estudiante.nombre, i, 0);
            tablaCalificaciones.setValueAt(estudiante.nota_uno, i, 1);
            tablaCalificaciones.setValueAt(estudiante.nota_dos, i, 2);
            tablaCalificaciones.setValueAt(estudiante.nota_tres, i, 3);
            tablaCalificaciones.setValueAt(estudiante.nota_cuatro, i, 4);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAprobados;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMenor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNotaCuatro;
    private javax.swing.JLabel lblNotaDos;
    private javax.swing.JLabel lblNotaTres;
    private javax.swing.JLabel lblNotaUno;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel panelDos;
    private javax.swing.JPanel panelUno;
    private javax.swing.JTable tablaCalificaciones;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNotaCuatro;
    private javax.swing.JTextField txtNotaDos;
    private javax.swing.JTextField txtNotaTres;
    private javax.swing.JTextField txtNotaUno;
    // End of variables declaration//GEN-END:variables
}
